apiVersion: v1
kind: Service
metadata:
  name: store-frontend-service
spec:
  selector:
    app: store-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
