apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: store-frontend
  template:
    metadata:
      labels:
        app: store-frontend
    spec:
      containers:
        - name: store-frontend
          image: likeahim/store-frontend:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: store-frontend
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: store-frontend
