apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: cm9vdHBhc3N3b3Jk # base64 for "rootpassword"
  mysql-database: c3RvcmVkYg==          # base64 for "storedb"
  mysql-user: dXNlcg==                  # base64 for "user"
  mysql-password: cGFzc3dvcmQ=          # base64 for "password"
