apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notifications-api
  template:
    metadata:
      labels:
        app: notifications-api
    spec:
      containers:
        - name: notifications-api
          image: likeahim/notifications-api:latest
          envFrom:
            - configMapRef:
                name: notifications-api-config
          ports:
            - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: notifications-api
spec:
  ports:
    - port: 5001
      targetPort: 5001
  selector:
    app: notifications-api
