apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: products-api
  template:
    metadata:
      labels:
        app: products-api
    spec:
      containers:
        - name: products-api
          image: likeahim/products-api:latest
          envFrom:
            - configMapRef:
                name: products-api-config
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: products-api
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: products-api
